export const Permissions = {
  AuditLogView: "audit_log.view",
  CustomersView: "customers.view",
  InventoryStockLedgerView: "inventory.stock_ledger.view",
  InventoryWarehouseManage: "inventory.warehouse.manage",
  ItemsView: "items.view",
  ProcurementPurchaseOrderView: "procurement.purchase_order.view",
  ProcurementPurchaseReceiptView: "procurement.purchase_receipt.view",
  ProcurementPurchaseReturnView: "procurement.purchase_return.view",
  SettingsInvitationsManage: "settings.invitations.manage",
  SettingsOrganizationManage: "settings.organization.manage",
  SettingsProfilesManage: "settings.profiles.manage",
  SettingsRolesManage: "settings.roles.manage",
  SettingsSecurityManage: "settings.security.manage",
  SettingsSessionsManage: "settings.sessions.manage",
  SettingsUomsManage: "settings.uoms.manage",
  SettingsUsersManage: "settings.users.manage",
  ShortageView: "inventory.shortage.view",
  SuppliersView: "suppliers.view",
  SupplierFinancialsPayablesView: "supplier_financials.payables.view",
  UomsManage: "settings.uoms.manage",
} as const;
